package dev.gaphunter.dockerfilelayersizecompanion.size

import dev.gaphunter.dockerfilelayersizecompanion.parse.CopyArgs
import java.io.File

/**
 * The real, honest result of trying to size a `COPY`/`ADD` instruction.
 * Only [Computed] carries a number -- every other case is a distinct,
 * named reason the plugin is refusing to invent one. See README
 * "What a number means (and when there isn't one)" for the full
 * user-facing explanation of each case.
 */
sealed class LayerSizeResult {
    /** [bytes] is the real sum of on-disk file sizes for every resolved, non-ignored source. */
    data class Computed(val bytes: Long, val dockerignoreApplied: Boolean) : LayerSizeResult()

    /** `COPY --from=<stage>` copies from a previous build stage's filesystem, not the local build context -- genuinely not computable without running the build. */
    object FromBuildStage : LayerSizeResult()

    /** A source path uses wildcard/glob syntax (`*.jar`) this v0.1 scanner doesn't expand -- documented limitation, not a silent wrong answer. */
    object UnresolvedWildcard : LayerSizeResult()

    /** None of the declared sources exist on disk relative to the build context -- e.g. the file is generated by an earlier, un-run build step. */
    object SourceNotFound : LayerSizeResult()

    /** The instruction's arguments couldn't be parsed at all (empty, malformed). */
    object Unparseable : LayerSizeResult()
}

/**
 * Resolves `COPY`/`ADD` source paths against the real local filesystem
 * and sums their on-disk size -- 100% static analysis, no Docker daemon,
 * no build. [buildContextDir] is the directory the Dockerfile itself
 * lives in (v0.1 always treats the Dockerfile's own directory as the
 * build context root; a `docker build -f sub/Dockerfile ..` context
 * override can't be observed from inside the editor, see README "Known
 * limitations").
 */
object LayerSizeCalculator {

    fun compute(copyArgs: CopyArgs, buildContextDir: File, dockerignore: DockerignoreMatcher): LayerSizeResult {
        if (copyArgs.fromStage != null) return LayerSizeResult.FromBuildStage
        if (copyArgs.sources.isEmpty()) return LayerSizeResult.Unparseable
        if (copyArgs.sources.any { it.contains('*') || it.contains('?') }) return LayerSizeResult.UnresolvedWildcard

        var total = 0L
        var anyFound = false
        var ignoreApplied = false

        for (source in copyArgs.sources) {
            // A source starting with "/" is still relative to the build
            // context in real Docker semantics (there's no escaping the
            // context), so strip any leading slash before resolving.
            val relative = source.removePrefix("./").trimStart('/')
            if (relative.isEmpty() || relative == ".") {
                // `COPY . .` -- whole build context.
                val (size, hadIgnored) = sizeOfTree(buildContextDir, buildContextDir, dockerignore)
                total += size
                anyFound = true
                if (hadIgnored) ignoreApplied = true
                continue
            }

            val target = File(buildContextDir, relative)
            if (!target.exists()) continue
            if (dockerignore.isIgnored(relative)) {
                ignoreApplied = true
                continue
            }
            anyFound = true
            if (target.isDirectory) {
                val (size, hadIgnored) = sizeOfTree(target, buildContextDir, dockerignore)
                total += size
                if (hadIgnored) ignoreApplied = true
            } else {
                total += target.length()
            }
        }

        if (!anyFound) return LayerSizeResult.SourceNotFound
        return LayerSizeResult.Computed(total, ignoreApplied)
    }

    /** Recursively sums file sizes under [dir], skipping anything [dockerignore] excludes (path relative to [contextRoot]). */
    private fun sizeOfTree(dir: File, contextRoot: File, dockerignore: DockerignoreMatcher): Pair<Long, Boolean> {
        var total = 0L
        var anyIgnored = false
        val children = dir.listFiles() ?: return 0L to false
        for (child in children) {
            val relative = contextRoot.toPath().relativize(child.toPath()).toString().replace(File.separatorChar, '/')
            if (dockerignore.isIgnored(relative)) {
                anyIgnored = true
                continue
            }
            if (child.isDirectory) {
                val (size, ignored) = sizeOfTree(child, contextRoot, dockerignore)
                total += size
                if (ignored) anyIgnored = true
            } else {
                total += child.length()
            }
        }
        return total to anyIgnored
    }

    /** Human-readable size, same binary-unit convention Docker/most IDEs use (1024-based, not 1000-based). */
    fun formatBytes(bytes: Long): String {
        if (bytes < 1024) return "$bytes B"
        val units = arrayOf("KB", "MB", "GB", "TB")
        var value = bytes.toDouble()
        var unitIndex = -1
        while (value >= 1024 && unitIndex < units.size - 1) {
            value /= 1024
            unitIndex++
        }
        return "%.1f %s".format(value, units[unitIndex])
    }
}
